### ISSUE TITLE
Help with function

### ISSUE THREAD

**Issue by mwhiteaz** [Watts-College/cpp-526-sum-2022#1]
Hi there! I am so stumped on this functions task. Please see my latest attempt and let me know what I'm doing wrong. Thanks! --Mary

convertToCelsius <- function(temp.in.fahreheit, temp.in.celsius) {
temp.in.celsius <- (temp.in.fahrenheit-32)*5/9
temp.in.fahrenheit <- 212
convertToCelsius(temp.in.fahrenheit)
return (temp.in.celsius)}

**Comment by Daniel-mhrb** [comment]
Hi,
I think in the function you just need to have temp.in.fahreheit, 
also, it was asked to round it and then we need to do the return.

here is my code:

```r
convert.to.celsius <- function(fahrenheit){
  celsius <- (fahrenheit - 32) * (5 / 9)
  celsius <- round(celsius,2)
  return(celsius)
}
convert.to.celsius(212)
```

**Comment by mwhiteaz** [comment]
Thank you, Daniel! I just tried to copy and paste yours again and this time it worked!! I think I forgot the final line.
