### ISSUE TITLE
Logical operators question

### ISSUE THREAD

**Issue by mwhiteaz** [Watts-College/cpp-526-sum-2022#2]
Hi all, just checking in to see how you wrote up this piece from the lesson this week. Not sure I did it right...

# everyone that scored over 20 on the strength test
these.strength <- dat$strength > 20
dat[ these.strength , "name"] 

My results came back like this: 
[1] frank wanda nancy
Levels: frank nancy sanjay wanda

**Comment by gmcirco** [comment]
That looks correct: the code `these.strength <- dat$strength > 20` will give you a vector of `TRUE` and `FALSE` values that correspond to people who had strength scores over 20. The second line gets the names of the people who scored over 20 - which was frank wanda and nancy.
