### ISSUE TITLE
Knit to HTML

### ISSUE THREAD

**Issue by Daniel-mhrb** [Watts-College/cpp-526-sum-2022#4]
I can not knit my new .rmd file while using the new packages and library and also the LAB-02 Template file.
Can anyone help me with how I can fix that?

I also had a problem with the installing packages, but I think they have been installed. 
<img width="952" alt="Screen Shot 2022-05-27 at 11 22 29 AM" src="https://user-images.githubusercontent.com/105667740/170769610-32179a57-0c39-4fec-a29b-976a00e8e0ff.png">

**Comment by gmcirco** [comment]
That error looks like it is related to rgdal installation. Make sure it is properly installed and the code for loading it in has been done in prior steps.
