### ISSUE TITLE
1. Plots/maps are not knitting correctly 2. Markdown 3. Visual Mode

### ISSUE THREAD

**Issue by JAHirsh** [Watts-College/cpp-526-sum-2022#5]
Hi, I have a few questions and would appreciate any guidance:
1. I'm having trouble getting the plots to show up correctly when I knit. I'm able to see the red areas on my plots in R Studio, but they are all grey on the document that gets created when I knit. 
2. I'm also a little confused about Markdown and how I should be applying it to this lab. 
3. If I click on Visual mode, then return to Source, backslashes are added to my code. Why is this?
Thanks!!!
Jessica

**Comment by gmcirco** [comment]
Do you have any reproducible code? Some examples would be helpful so I might see exactly what your code looks like. Often times any issues might be related to how your markdown code is formatted. Generally speaking you should just be putting new code inside the code blocks that are marked off with: ```{r}
