### ISSUE TITLE
ShinyExample-01.rmd error

### ISSUE THREAD

**Issue by lingarfield** [Watts-College/cpp-526-sum-2022#8]
Hello,
I tried to run the Shiny demo with Old Faithful and it errors. Both in the Cloud R and the desktop R. This code when ran:

selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)

Returns this error:

Error in selectInput("n_breaks", label = "Number of bins:", choices = c(10,  : 
  could not find function "selectInput"

I noticed there isn't an Input ID in the example, and wasn't sure if that was the issue? I definitely feel very much out of my depth at this point.

**Comment by gmcirco** [comment]
Hi Lisa,

With a shiny app, you have to run the entire set of code (not just a code block). This is because it's an interactive application and the entire code has to run for it to work. Make sure you are hitting the "Run Document" button at the top of your RStudio document.

**Comment by lingarfield** [comment]
Yeah i figured that out. Lol

I spent several hours yesterday reading and watching the video a few times. I am not feeling very confident. I don’t really understand a lot of the code especially on the server side. I am going to try tonight and see what happens. 

I feel like this got really hard really quickly!!

---------------
Lisa Ingarfield, PhD
She/her
Owner/Consultant
Defi Consulting
***@***.***
970-219-7595
www.deficonsulting.org

Evaluation and Research - DEI Organizational Analysis - Communication and Policy Strategies
