### ISSUE TITLE
Knit to HTML

### ISSUE THREAD

**Issue by Daniel-mhrb** [Watts-College/cpp-526-sum-2022#9]
Hi all,

I am wondering if anyone knows how to knit the Lab_04 file to HTML?

I can run the document and see the result, but I do not know how to get HTML export.

Any help would be greatly appreciated!

Thanks

**Comment by gmcirco** [comment]
Hi Daniel,

Lab 4 is "special" because it is an Shiny object. This means it is rendered as an interactive application. So you can't render it to a .html object. However, you can just submit your .RMD file and I can run your application on my computer!

**Comment by Daniel-mhrb** [comment]
Thank you
